### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by cdiaz** [nestjs/typeorm#108]
## I'm submitting a...
[ ] Regression
[ ] Bug report
[X ] Feature request
[ ] Documentation issue or request

## Current behavior
there is no support to use transactions in an integrated way with the repositories of @nestjs / typeorm

## Expected behavior
Add support for  @Transaction, @TransactionManager and @TransactionRepository TypeORM decorators

**Comment by kamilmysliwiec** [comment]
As far as I know, TypeORM transaction decorators are going to be removed eventually.

**Comment by luqezman** [comment]
News?

**Comment by kamilmysliwiec** [comment]
https://github.com/typeorm/typeorm/issues/3251

**Comment by moulinraphael** [comment]
Hello @kamilmysliwiec 

First of all, thanks a lot about `nestjs` and your time answering on our issues ^^ 
I'm very interested about this subject on `transactions` with Typeorm because my application is becoming large and I need to split all instructions into specific services. However it is not clear how to maintain transactions with multiple services and it seems such decorators as `@Transaction` / `@TransactionManager` could be the solution. It's a shame if they will be removed.

What do you suggest in such a case (for example when a main service call two other services, and an error occured in the second call) ?

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/database#transactions

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
