### ISSUE TITLE
8.1.0 introduces backward incompatible typeorm 0.2 > 0.3 

### ISSUE THREAD

**Issue by acuthbert** [nestjs/typeorm#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you upgrade to 8.1.0 and were using typeorm 0.2 in your project, your project will not build.

### Minimum reproduction code

-

### Expected behavior

typeorm 0.3 is a backward incompatible change over 0.2 but nest has moved from 8.0 to 8.1 which for must of us would be considered a minor update (semver etc.). We have found that this update has broken the build of projects and moving to typeorm 0.3 might be non trivial.

### Package version

8.1.*

### NestJS version

8.*

### Node.js version

14*

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [X] Linux

**Comment by darrena092** [comment]
> I think we won't support typeorm 0.2 anymore
It does seem like a problem though that a minor release would introduce breaking changes. typeorm 0.3 introduces breaking changes and by requiring it, so does this package. This feels like it should be a major increment.

**Comment by janvanhest** [comment]
Maybe it is a good idea to provide some instructions in https://docs.nestjs.com/migration-guide regarding this issue and how to handle this breaking issue.

**Comment by kamilmysliwiec** [comment]
Yeah, I figured that might be an issue, that's why we waited so long before we merged that PR & released a new version. Unfortunately, we can't really wait another month or two locking everyone on typeorm v0.2 just so we can release a new version of this package together with Nest v9. This is a thin integration package that respects NestJS's semantic versioning and is supposed to stay in line with Nest main packages. We can't publish a new major release every time TypeORM introduces a breaking change (as `@nestjs/typeorm` would quickly become _not in line_ with other packages like `@nestjs/core` etc.).

I just pushed a commit that introduces a tiny backward compatibility layer https://github.com/nestjs/typeorm/commit/8f4f57ddeeadb1fe4fc6b042046bb3e767e09983 that fixes issues brought up by @micalevisk above. Published as `@nestjs/typeorm@8.1.1`. This should make things simpler but ** keep in mind that it wont fix all issues**.

If you're highly dependent on TypeORM features like custom repositories, you should keep using:
- `typeorm@0.2.4x`
- `@nestjs/typeorm@8.0.4` (simply lock this version in your `package.json` file)
