### ISSUE TITLE
`onModuleDestroy` cannot close connection when using forRootAsync

### ISSUE THREAD

**Issue by scott-ho** [nestjs/typeorm#184]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

unable to close typeorm connection, fail to destroy typeorm core module

## Expected behavior

destroy typeorm core module correctly

## Minimal reproduction of the problem with instructions

`onModuleDestroy` is using the wrong token to retrieve the connection if using `forRootAsync`,
https://github.com/nestjs/typeorm/blob/master/lib/typeorm-core.module.ts#L105

see https://github.com/scott-ho/nest-typeorm-problem

## What is the motivation / use case for changing the behavior?

fix the bug

## Environment

<pre><code>
Nest version: 6.6.6

 
For Tooling issues:
- Node version: v10.14.2
- Platform:  Windows

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository (cloneable) which reproduces your issue.

**Comment by scott-ho** [comment]
@kamilmysliwiec minimal repro created and updated above.

**Comment by kamilmysliwiec** [comment]
As I thought, it's related to the `name` parameter.

If you use a single connection across your app, you should remove the `name` parameter because it indicates that you will use multiple of them.

```typescript
TypeOrmModule.forRootAsync({
   useFactory: async () => {
      const { name, ...options } = await getConnectionOptions('development');
      return options;
   },
}),
```

That will fix your issue.

However, if you really want to use named connections (and multiple connections), you have to pass an extra `name` parameter to the `forRootAsync()` method so we can distinguish your connections.

```typescript
TypeOrmModule.forRootAsync({
      name: 'development',
      useFactory: () => {
        return getConnectionOptions('development');
      },
}),
```

In this case, though, you have to be aware of a few things. First, instead of using this:

```typescript
constructor(private readonly connection: Connection) {}
```
You have to tell the DI system which connection inject:
```typescript
constructor(
    @InjectConnection('development') private readonly connection: Connection,
) {}
```

Likewise, with repositories:

```typescript
constructor(
    @InjectRepository(UserEntity, 'development')
    private readonly userRepository: Repository<UserEntity>,
) {}
```
