### ISSUE TITLE
How to inject a custom repository

### ISSUE THREAD

**Issue by andrzejpakula** [nestjs/typeorm#39]
[x] Support request

Hi. How to inject a custom repository http://typeorm.io/#/custom-repository ? And second question [this](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md#using-custom-repositories-in-transactions-or-why-custom-repositories-cannot-be-services) indicates that we shouldn't be creating services from custom repositories, especially if you want to use transactions. What do you think
? Best Regards

**Comment by xmlking** [comment]
I also see following implementation, but it doesn't work for me :(     

https://github.com/QuentinouLeTwist/nestjs-vuejs-boilerplate/tree/master/backend/src/modules/api/user

**Comment by andrzejpakula** [comment]
I think that this is not the way to solve this problem, because owner did not respond to the next comments in the thread https://github.com/nestjs/typeorm/issues/14. Functionality is theoretically merged, but it is hard for me to understand how to implement it only after the [changes](https://github.com/nestjs/typeorm/pull/18/files) .. A more important problem is that the documentation does not [recommend](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md#using-custom-repositories-in-transactions-or-why-custom-repositories-cannot-be-services) the global registration of custom repositories, as they are not a single instance and it may cause problems with transactions .

**Comment by xmlking** [comment]
Looks like custom repositories are  injected same way like entities 
 
https://github.com/evebook/api/tree/master/src/modules/character

**Comment by mentos1386** [comment]
@xmlking Yeah, they are injected same way as entities. It was added with this PR https://github.com/nestjs/typeorm/pull/12

It should probably be noted in documentation that there is a way of injecting them...

**Comment by kamilmysliwiec** [comment]
```
EDIT: It is documented in the docs https://docs.nestjs.com/techniques/database under Repository Pattern
```
So is there anything that still should be clarified?

**Comment by MattIzSpooky** [comment]
Hello everyone, I ran into the same issue and I finally figured it out how to do it after trying a bunch of things. I don't agree with the first answer given because you aren't supposed to make the repository a provider/service as is written [here](https://github.com/nestjs/typeorm/issues/14). This is not documented so that's why I'd like to share how I did it.

First create your **custom repository**. I threw in some useless functions to show that it works.
```ts
@EntityRepository(Author)
export class AuthorRepository extends Repository<Author> {
  test() {
    console.log('testasfasdfasdf');
  }
  customSave(entity) {
    return this.save(entity);
  }
}
````
Then go to your **feature module**
```ts
@Module({
  imports: [TypeOrmModule.forFeature([Author, AuthorRepository /* <--- put your custom repository here together with your entities */])],
  providers: [AuthorService, AuthorResolver],
})
export class TestModule {
}
````

Now we go to our **service**
```ts
@Injectable()
export class AuthorService {
  constructor(
    @InjectRepository(AuthorRepository)
    private readonly authorRepository: AuthorRepository, // <-- inject like this
  ) {
  }

  async create(author: AuthorInterface) {
    this.authorRepository.test();
    return await this.authorRepository.customSave(this.authorRepository.create(author));
  }
}
````

**Voila!** You're done, you can now use your custom repository as if it was a default repository but with your own extra goodies!

Some **proof** that it works:
I use GraphQL so here's the other code:
```ts
@Resolver('Author')
export class AuthorResolver {
  constructor(
    private readonly authorService: AuthorService,
    private readonly postsService: PostService,
  ) {
  }

  @Mutation('createAuthor')
  async createAuthor(obj, args, context, info) {
    return await this.authorService.create(args);
  }
}
````
Execute the mutation

![image](https://user-images.githubusercontent.com/26460447/44052644-6f31e404-9f3d-11e8-876d-ba53604e12ea.png)

Result

![image](https://user-images.githubusercontent.com/26460447/44052671-811d9758-9f3d-11e8-92b5-5cfe8d22f522.png)

Database

![image](https://user-images.githubusercontent.com/26460447/44052684-8cef43f6-9f3d-11e8-95dd-173f3e2a400d.png)

Console, to show that the `console.log` function is called.
![image](https://user-images.githubusercontent.com/26460447/44052827-0d11c6b2-9f3e-11e8-9e45-e652c96c1086.png)

**Comment by kamilmysliwiec** [comment]
Just created an issue in the documentation repository. I'll use @MattIzSpooky example and share solution very soon :)

**Comment by Roms1383** [comment]
> Looks like custom repositories are injected same way like entities
> 
> https://github.com/evebook/api/tree/master/src/modules/character

Sadly this link is broken 😿

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/database#custom-repository
