### ISSUE TITLE
Easy question: what is the purpose of the TYPEORM_MODULE_ID provider?

### ISSUE THREAD

**Issue by dfee** [nestjs/typeorm#514]
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

I've been studying this code as a pattern for another provider I'm building.

**Question**: what is the purpose of this code?
https://github.com/nestjs/typeorm/blob/beb59047f2eda9851f03233df7f55ce70b1410cb/lib/typeorm-core.module.ts#L93-L96

I see it came from this code commit: [bugfix: fix multiple forRootAsync calls](https://github.com/nestjs/typeorm/commit/e153bb9dccded065f186f1e2bd5723ab81090948)

The commit message is clear, but I've not come across any documentation for why something like this would be needed. Is it a left-over artifact, or is it still relevant – why?

As a bonus question: why go through the additional effort of having `TypeOrmModule` delegate the work to `TypeOrmCoreModule`... rather than just have `TypeOrmModule` do the work itself? And how can you get away with `TypeOrmModule` not exporting any providers and yet `Connection` and `Entities` are still available?

Thanks! @kamilmysliwiec

**Comment by devin-fee-ah** [comment]
So I've figured out the bonus question bit... with the help of @jmcdo29 on Discord (thank you!).

> why go through the additional effort of having TypeOrmModule delegate the work to TypeOrmCoreModule... rather than just have TypeOrmModule do the work itself?

This is largely around explicit sharing / least privilege. `EntityManager` and `Connection` are exposed globally (`TypeOrmCoreModule` is decorated with `Global()`), but to get access to the underlying repositories (specifically via the `InjectRepository()` decorator... and not just extract it from the `EntityManager`), you'd need to use `ForFeature`.

> And how can you get away with TypeOrmModule not exporting any providers and yet Connection and Entities are still available?

It's marked as `Global()`. I'd failed to see that last night.

---

So the final mystery is around _why_ we need this: https://github.com/nestjs/typeorm/blob/beb59047f2eda9851f03233df7f55ce70b1410cb/lib/typeorm-core.module.ts#L93-L96

only `ForRootAsync` creates that provider (and it's the only place where `TYPEORM_MODULE_ID` and `generateString` are used)... so no one is actually retrieving anything based on that (in this repo or any of the others under `@nestjs`...)

**Comment by dfee** [comment]
After looking through it further _and testing_, I believe this is unnecessary.

**Comment by kamilmysliwiec** [comment]
> why go through the additional effort of having TypeOrmModule delegate the work to TypeOrmCoreModule... rather than just have TypeOrmModule do the work itself? 

In the past, it wasn't possible to dynamically mark a dynamic module as global (only the static way was available). Hence, an additional global module.

> Question: what is the purpose of this code?

This code covers a fairly rare, edge-case. 

Basically, as we know, Nest modules are singletons. Dynamic modules can act as singletons as well as long as you pass the exact same options object to the static method (e.g. `forRoot()`). The modules compiler will then serialize your dynamic metadata and generate an equal hash associated with this particular dynamic module. Now, imagine that you have 2 `forRootAsync()` calls in your application to instantiate 2 DB connections. In both cases, you're using the "async factory" approach. Also, in both cases, you don't inject anything into a factory and use an arrow function (unnamed function). Thus, even though your async functions may return different options, the generated hash will be equal since we can't resolve providers before generating a module graph (which wouldn't make any sense either way). A unique ID (generated in the `typeorm-core.module` file covers this exact, described edge-case.
