### ISSUE TITLE
Dynamic credential/config rotation

### ISSUE THREAD

**Issue by krzysztof-miemiec** [nestjs/typeorm#557]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

As far as I understand, one may initialize TypeORM connection once, by creating a module and including static configuration. For example `createTypeOrmOptions()` in `TypeOrmOptionsFactory` is only called once, even if I manually close the connection.

## Expected behavior

I created a custom config module for continuously reading secrets/config from a file (i.e. volume attached to container in Kubernetes pod). `DynamicConfigModule` parses file and returns a config object - i.e. with Postgres credentials. As a result I can inject `DynamicConfigService` which provides an access to a `Promise<Config>` (for one-time use) or an `Observable<Config>` stream, which returns a new config whenever secret file changes.
I'd like to be able to pass this stream of configurations (i.e. with changing database username/password) to `@nestjs/typeorm` module and let it handle everything related to connection rotation.

## Minimal reproduction of the problem with instructions

https://gist.github.com/krzysztof-miemiec/0a54ccba47a89f405e8fcc40cca619b9
This is my current solution - custom service, which uses TypeORM and it's ConnectionManager to manage a pool of connections. There are a few cases to consider:
* when new config is received, we can't immediately close existing connection as running transactions fail
* whenever a service asks for repository/connection, it has to be provided as function, not as a hard reference bound to specific connection (it appears that current `@nestjs/typeorm` implementation binds to connection created on app start)
* after new connection is created, we should be able to access it from a service immediately (i.e. new connection is returned instead of old one)
* there's no way to drain old TypeORM connections, so we just wait for X minutes before closing them (at least I haven't found any way of draining db connections)
* we have to close all connections on teardown (especially those which are waiting to be closed in `setTimeout` in my code - that's a bug)

## What is the motivation / use case for changing the behavior?

I'd like to make use of [Hashicorp Vault dynamic database credentials](https://www.vaultproject.io/docs/secrets/databases) feature. It'd be perfect to have end-to-end best security practices experience built into Nest.js. 🎉 
I don't want to restart my server - to do it gracefully, I'd have to block incoming connections, reflect it via readiness healthcheck, bootstrap new server and wait for some time/close the server gracefully in order to not leave some users with 5xx errors. 🤔 

## Environment

<pre><code>
Nest version: 7.3.2

 
For Tooling issues:
- Node version: 12.x  
- Platform: macOS/Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Apologies for the delayed response!

Great questions @krzysztof-miemiec, let me try to address everything.

> As far as I understand, one may initialize TypeORM connection once, by creating a module and including static configuration. For example createTypeOrmOptions() in TypeOrmOptionsFactory is only called once, even if I manually close the connection.

Correct.

> I created a custom config module for continuously reading secrets/config from a file (i.e. volume attached to container in Kubernetes pod). DynamicConfigModule parses file and returns a config object - i.e. with Postgres credentials. As a result I can inject DynamicConfigService which provides an access to a Promise<Config> (for one-time use) or an Observable<Config> stream, which returns a new config whenever secret file changes. I'd like to be able to pass this stream of configurations (i.e. with changing database username/password) to @nestjs/typeorm module and let it handle everything related to connection rotation.

Unfortunately, `@nestjs/typeorm` covers quite simple use-cases in which applications rely on single or multiple, statically defined connections. These are initialized on the application bootstrap and closed within the `onApplicationShutdown()` hook. For more complex scenarios, like this one you described above (connection rotation) or multi-tenancy (e.g., request-scoped connections cached per tenant), we recommend following [this recipe](https://docs.nestjs.com/recipes/sql-typeorm) to build a dedicated typeorm module suitable and tailored to the application needs.

> https://gist.github.com/krzysztof-miemiec/0a54ccba47a89f405e8fcc40cca619b9
This is my current solution - custom service, which uses TypeORM and it's ConnectionManager to manage a pool of connections. 

Looks great! One thing to keep in mind is that `cleanup()` method will be executed twice (not sure if that's the intended behavior) since it's being called from 2 teardown-related lifecycle hooks (`onModuleDestroy()`, `onApplicationShutdown()`).

> whenever a service asks for repository/connection, it has to be provided as function, not as a hard reference bound to specific connection (it appears that current @nestjs/typeorm implementation binds to connection created on app start)

I'm wondering, perhaps, creating a `Proxy` that mimics repository classes and wraps the logic of picking the repository from the right connection (using your `DatabaseService`) should allow you register repositories as injectable providers (using the Custom Providers technique) and hence, inject them via constructor to other services. So in fact, each service would interact with your proxy but that would be hidden from the end-user (developer) and explicitly calling a function to obtain a repository reference wouldn't be needed (proxy would be responsible for that).

> after new connection is created, we should be able to access it from a service immediately (i.e. new connection is returned instead of old one)

For this, you could consider following a similar idea as described above^, this time creating a `Proxy` that represents a connection. 

> we have to close all connections on teardown (especially those which are waiting to be closed in setTimeout in my code - that's a bug)

You can close connections in the app shutdown hook (but I can see in the gist that you've already figured that out!) :)

> when new config is received, we can't immediately close existing connection as running transactions fail
> there's no way to drain old TypeORM connections, so we just wait for X minutes before closing them (at least I haven't found any way of draining db connections)

Consider asking these questions in the typeorm repo (or our Discord channel since typeorm isn't up to date with issues maintenance), perhaps there's a clean way to accomplish this

**Comment by krzysztof-miemiec** [comment]
I really like an idea of using a `Proxy` object (it has performance implication though 🤔). I'm not sure if TypeORM repositories cache fields of connection instance - if they don't, then I may be able to simply create a proxy of connection which rotates "itself" underneath.
BTW. Is it enough to perform cleanup only in `onModuleDestroy()` hook?

**Comment by kamilmysliwiec** [comment]
> BTW. Is it enough to perform cleanup only in onModuleDestroy() hook? I'm thinking of cleanup possibility in both tests and live app.

Yes. Basically either one would be fine (`onModuleDestroy` or `onApplicationShutdown`). Both are being executed on `app.close()` call and when any shutdown signal is sent (just make sure to call `app.enableShutdownHooks()` in both `main.ts` and test files). :)
