### ISSUE TITLE
Cannot inject repos into other (custom) repos

### ISSUE THREAD

**Issue by CWSpear** [nestjs/typeorm#98]
## I'm submitting a...

<pre><code>[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request</code></pre>

## Current behavior
When injecting a custom repository into another custom repository, what _actually_ gets injected at runtime is the `EntityManager`.

## Expected behavior
The actual custom repo you're trying to inject should be injected.

## Minimal reproduction of the problem with instructions
The minimum reproducible repo is here with instructions on how to start the app and a cURL command to see the bug in action:

https://github.com/CWSpear/nestjs-typeorm-bug

If you want to filter out the code auto-generated in the CLI, you can view a diff of the changes after the initial code was generated: https://github.com/CWSpear/nestjs-typeorm-bug/compare/generated...master

The gist, tho is:

```ts
@EntityRepository(Agency)
export class AgencyRepository extends Repository<Agency> {
  constructor(
    @InjectRepository(UserRepository)
    private userRepo: UserRepository,
  ) {
    super();
    // we expect this to print `UserRepository`, but it prints `EntityManager`
    console.log(this.userRepo.constructor.name);
  }
```

## What is the motivation / use case for changing the behavior?
This is a trivial example, and there are obviously easier ways to accomplish what I want within TypeORM (there will be at least one person who is gonna point out, "Well, you can just create a `@OneToMany` between `Agency` and `User`" 😁), but I was trying to create very simple example that should work regardless.

But the general use-case is for very specific, complex relationships, I'd like to be able to leverage shared code in repos efficiently.

## Current workaround
Currently, I'm doing this:
```ts
this.userRepo = this.manager.getCustomRepository(UserRepository);
```

but then it gets more complicated to test, because I can no longer override the provider with my mocks in tests, etc. It would be much preferable if I could properly inject it.

## Environment

<pre><code>Nest version: 6.3.0

 
For Tooling issues:
- Node version: v11.14.0
- Platform:  Mac</code></pre>

**Comment by Diluka** [comment]
crashed when upgrade `6.0` to `6.1`

something like this. crashed when inject `repo` into `service`

**Comment by kamilmysliwiec** [comment]
Custom repositories are being instantiated by `typeorm` library, not `@nestjs/core` which means that you won't be able to use our dependency injection mechanism in there. Nonetheless, you can always grab another custom repository instance using an `EntityManager` (passed to custom repos by typeorm).

PS. @Diluka - update your library to `@nestjs/typeorm@6.1.1`

**Comment by BatuhanW** [comment]
@CWSpear  I think it's an antipattern to inject a repository, into another repository.

I believe, repositories should have a single responsibility and shouldn't interact with other repositories. It should be solely about database interactions. Just do things like creating, updating, assigning and no more.

Let's assume we should automatically generate a User for every created Agency;

And we have these;

- User Repository
- Agency Repository
- Agency Service

Here, we can inject both repositories into the Agency Service and this service should be responsible for invoking functions from both repositories. (So we can easily mock these repository methods for tests and assure they indeed try to create both Agency and User).

What do you think?

**Comment by Irungaray** [comment]
Hi, I came to this issue several times in the current week as I was debugging something similar that we have done in my company.

Attempting to kill the monolith, we created 2 libraries, 'common' and 'core'.
Common contains plain objects like DTOs, enums, claims and entities (and its migrations).
Core contains the files that handles bussiness logic such as services, repositories and mappers.

We came onto this and other errors by the like when we started to consume 'core' in a new microservice.

The problem (i think) was that we were installing the 'core' package from the local folder, and it came with the package's node_modules, so all the code in 'core', specifically, everything from 'typeorm', was being instantiated from the package's node_modules, and not from the consumer node_modules.

The solution was to publish the package and install it from the NPM registry instead of installing it from a local folder.

Hope it helps someone in the future.
